# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nDZry523UnwS0iVXULfPwpNsYVf4cqNO

##Python Mini-Project - Pandas Project - Data Analysis on Cafe sales data
"""

# ==============================
# CAFETERIA SALES DATA ANALYSIS
# ==============================

# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv("Cafeteria.csv")

# Display first 5 rows (Tabular)
print("\n🔹 Sample Data:")
print(df.head().to_string(index=False))


# ==============================
# 1. DATA CLEANING
# ==============================

# Basic Info in table format
info_df = pd.DataFrame({
    "Column": df.columns,
    "Non-Null Count": df.notnull().sum().values,
    "Data Type": df.dtypes.values
})
print("\n🔹 Dataset Information:")
print(info_df.to_string(index=False))


# Missing values in table format
missing_df = df.isnull().sum().reset_index()
missing_df.columns = ["Column", "Missing Values"]
print("\n🔹 Missing Values Report:")
print(missing_df.to_string(index=False))


# Drop rows with missing critical values
df = df.dropna(subset=['Transaction Date', 'Item',
                       'Quantity', 'Price Per Unit'])

# Remove unwanted values
df = df[~df.isin(['UNKNOWN', 'ERROR']).any(axis=1)]

# Convert data types
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'], errors='coerce')
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')
df['Price Per Unit'] = pd.to_numeric(df['Price Per Unit'], errors='coerce')

# Drop invalid rows
df = df.dropna()

# Remove duplicates
df = df.drop_duplicates()

# Create total price
df['Total Price'] = df['Quantity'] * df['Price Per Unit']


# ==============================
# 2. EXPLORATORY DATA ANALYSIS
# ==============================

# Summary statistics in tabular format
summary_df = df[['Quantity', 'Price Per Unit', 'Total Price']].describe().round(2)
print("\n🔹 Summary Statistics:")
print(summary_df.to_string())


# Correlation table
corr_df = df[['Quantity', 'Price Per Unit', 'Total Price']].corr().round(2)
print("\n🔹 Correlation Matrix:")
print(corr_df.to_string())


# Heatmap
sns.heatmap(corr_df, annot=True)
plt.title("Correlation Heatmap")
plt.show()


# ==============================
# 3. SALES ANALYSIS
# ==============================

# Extract month
df['Month'] = df['Transaction Date'].dt.month

# Monthly Sales Table
monthly_sales = df.groupby('Month')['Total Price'].sum().reset_index()
monthly_sales.columns = ["Month", "Total Revenue"]
print("\n🔹 Monthly Sales:")
print(monthly_sales.to_string(index=False))


# Plot
monthly_sales.plot(x='Month', y='Total Revenue', kind='bar')
plt.title("Monthly Sales")
plt.show()


# Top Selling Items Table
top_items = df.groupby('Item')['Quantity'].sum().reset_index()
top_items = top_items.sort_values(by='Quantity', ascending=False).head(10)
print("\n🔹 Top Selling Items:")
print(top_items.to_string(index=False))


# Plot
top_items.plot(x='Item', y='Quantity', kind='bar')
plt.title("Top Selling Items")
plt.show()


# Peak Sales Day Table
df['Day'] = df['Transaction Date'].dt.day_name()

peak_day = df.groupby('Day')['Total Price'].sum().reset_index()
peak_day = peak_day.sort_values(by='Total Price', ascending=False)

print("\n🔹 Peak Sales by Day:")
print(peak_day.to_string(index=False))


# ==============================
# END OF PROJECT
# ==============================